config/routes.rb
PpPeru::Application.routes.draw do

  
  ComfortableMexicanSofa::Routing.admin(:path => '/admin/cms')

  # get "home/index"

  devise_for :users

  # root :to => "home#index"
  
  resources :usuarios, controller: :users do
    resources :seguidores, controller: 'users_activities/followers', only: [:create, :destroy]
  end

  match '/auth/:provider/callback', to: 'authentications#create'


  resources :topics, only: [:index]
  
  resources :news_actors, only: [:show, :index] do
    collection do
      post :rates
    end
  end

  scope '/centro_de_medios' do
    resources :noticias, controller: :news, only: [:show, :index] do
      resources :comentarios, controller: :annotations, only: [:create, :new]
      collection do
        post :rates
      end
    end
  end
  
  scope '/centro_educacional' do
    resources :entradas, controller: :entries, only: [:show, :index] do
      resources :comentarios, controller: :annotations, only: [:create, :new]
    end
  end
  
  scope '/centro_de_debate' do
    resources :debates, controller: :discussions, only: [:show, :index] do
      resources :comentarios, controller: :annotations, only: [:create, :new]
      resources :votes, controller: 'discussions_activities/votes', only: :create
    end
  end
  
  scope '/propuesta_ciudadana' do
    resources :propuestas, controller: :proposals, except: :destroy do
      resources :comentarios, controller: :annotations, only: [:create, :new]
      resources :votes, controller: 'proposals_activities/votes', only: :create
    end
  end
  
  scope '/objetivos_estrategicos' do
    resources :buenas_practicas, controller: :strategic_objectives, only: [:index]
    resources :objetivos, controller: :objectives, only: [:index]
  end

  scope '/actores_politicos' do
    resources :candidatos, controller: :news_actors, only: [:index, :show]
  end
  
  
  
  resources :annotations, only: :index do
    resources :reports, only: :create
    resources :reviews_admins, only: :create
  end

  namespace :admin do
    root to: 'home#index'
    resources :news do
      resource :publish, controller: 'news_actions/publish', only: :create
      resource :archive, controller: 'news_actions/archive', only: :create
    end
    
    resources :discussions do
      resources :open_discussion, controller: 'discussions_actions/open_discussion', only: :create
      resources :close_discussion, controller: 'discussions_actions/close_discussion', only: :create
      resources :archive_discussion, controller: 'discussions_actions/archive_discussion', only: :create
    end
    

    resources :proposals do
      resource :publish, controller: 'proposals_actions/publish', only: :create
      resource :archive, controller: 'proposals_actions/archive', only: :create
    end

    resources :entries do
      resource :publish, controller: 'entries_actions/publish', only: :create
      resource :archive, controller: 'entries_actions/archive', only: :create
    end
    
    resources :topics, only: [:index, :create]
    resources :news_actors
    resources :groups
    resources :users
    resources :attendees
    resource :configuration, only: [:show, :edit, :update]
    resources :strategic_objectives do
      resources :annotations, only: [:create, :new]
    end
    
    resources :roles, only: :index do
      resources :role_permissions, only: [:index, :create]
    end
  end

  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)
end

app/controllers/admin/configurations_controller.rb
class Admin::ConfigurationsController < Admin::BaseController

  def show
    authorize! :config_site, :show
  end
  
  def edit
    authorize! :config_site, :edit
  end
  
  def update
    authorize! :config_site, :update
    
    upload_background_image if params[:background_image][:file].present?
    upload_style_images
    set_boolean_values
    
    params[:setting].each do |setting|
      Setting[setting.first] = setting.last
    end
    redirect_to admin_configuration_url
  end
  
  private
  
  def upload_background_image
    uploader = BackgroundImageUploader.new
    file = params[:background_image].delete(:file)
    uploader.image_x = params[:background_image][:image_x]
    uploader.image_y = params[:background_image][:image_y]
    uploader.store!(file)
    Setting.background_image = uploader.url
  end
  
  def upload_style_images
    unless Setting.color1.equal?(settings[:color1]) || Setting.color2.equal?(settings[:color2]) || Setting.color3.equal?(settings[:color3]) || Setting.color4.equal?(settings[:color4]) || Setting.color5.equal?(settings[:color5])
      ImageCreator.new(:footer, Setting.array_colors).upload_images
      ImageCreator.new(:header, Setting.array_colors).upload_images
    end
  end
  
  def set_boolean_values
    params[:setting][:public_registration] = !!settings[:public_registration]
    params[:setting][:centro_de_noticas_visible] = !!settings[:centro_de_noticas_visible]
    params[:setting][:centro_educacional_visible] = !!settings[:centro_educacional_visible]
    params[:setting][:centro_de_debates_visible] = !!settings[:centro_de_debates_visible]
    params[:setting][:propuesta_ciudadana_visible] = !!settings[:propuesta_ciudadana_visible]
    params[:setting][:objetivos_visible] = !!settings[:objetivos_visible]
  end
  
  def settings
    params[:setting]
  end
end

app/helpers/admin/configurations_helper.rb
module Admin::ConfigurationsHelper
end

app/views/admin/configurations/show.html.haml
.row-fluid
  .box
    .box-content
      .page-header
        %h1 Configuraciones
      = link_to 'Editar configuraciones', edit_admin_configuration_path, class: ['btn', 'btn-primary']
      
      %ul.nav.nav-tabs
        %li.active
          %a{href: '#general', 'data-toggle' => "tab"} General
        %li
          %a{href: '#estilos', 'data-toggle' => "tab"} Diseño
        %li
          %a{href: '#tipografia', 'data-toggle' => "tab"} Tipografia
        %li
          %a{href: '#home', 'data-toggle' => "tab"} Home
        %li
          %a{href: '#tabs', 'data-toggle' => "tab"} Secciones
      
      .tab-content
        #general.tab-pane.active
          %dl
            %dt Nombre del sitio:
            %dd= Setting.site_name
            
            %dt Comentarios:
            %dd= Setting.comments_limit.to_i > 0 ? "#{Setting.comments_limit} caracteres máximo" : 'Ilimitados'
            
            %dt Registro publico:
            %dd
              - if Setting.public_registration
                %span.label.label-success
                  Si
              - else
                %span.label.label-important
                  No
        
        #estilos.tab-pane
          %dl
            %dt Color 1:
            %dd
              .config-color-sample{style: "background-color: #{Setting.color1};"}
              = Setting.color1
            
            %dt Color 2:
            %dd
              .config-color-sample{style: "background-color: #{Setting.color2};"}
              = Setting.color2
            
            %dt Color 3:
            %dd
              .config-color-sample{style: "background-color: #{Setting.color3};"}
              = Setting.color3
            
            %dt Color 4:
            %dd
              .config-color-sample{style: "background-color: #{Setting.color4};"}
              = Setting.color4
        
            %dt Color 5:
            %dd
              .config-color-sample{style: "background-color: #{Setting.color5};"}
              = Setting.color5
              
            - if Setting.footer_image.present?
              %dt Imagen del footer:
              %dd= image_tag Setting.footer_image
              
            - if Setting.header_image.present?
              %dt Imagen del header:
              %dd= image_tag Setting.header_image

            - if Setting.background_image.present?
              %dt Imagen Principal:
              %dd= image_tag Setting.background_image 
        
        #tipografia.tab-pane
          .tabbable.tabs-left
            %ul.nav.nav-tabs
              %li.active
                %a{href: '#tipografia_texto', 'data-toggle' => "tab"} Texto
              %li
                %a{href: '#tipografia_enlaces', 'data-toggle' => "tab"} Enlaces
              
            .tab-content
              #tipografia_texto.tab-pane.active
                %dl
                  %dt Tipografia:
                  %dd 
                    %span{style: "font-family:#{raw Setting.text_font_family}"}= Setting.text_font_family_name
                  
                  %dt Tamaño:
                  %dd 
                    %span{style: "font-size:#{Setting.text_font_size}"}= "#{Setting.text_font_size}px"
                  
                  %dt Color:
                  %dd
                    %span{style: "color:#{Setting.text_color}"}= Setting.text_color
              
              #tipografia_enlaces.tab-pane
                %dl
                  %dt Color del enlace:
                  %dd
                    %span{style: "color:#{Setting.link_color}"}= Setting.link_color
                  
                  %dt Color del enlace activo:
                  %dd
                    %span{style: "color:#{Setting.link_color_hover}"}= Setting.link_color_hover
          
        #home.tab-pane=  Setting.home_main_content.html_safe if Setting.home_main_content.present?
        
        #tabs.tab-pane
          .tabbable.tabs-left
            %ul.nav.nav-tabs
              %li.active
                %a{href: '#centro_de_noticias', 'data-toggle' => "tab"} Centro de noticias
              %li
                %a{href: '#centro_educacional', 'data-toggle' => "tab"} Centro educacional
              %li
                %a{href: '#centro_de_debates', 'data-toggle' => "tab"} Centro de debates
              %li
                %a{href: '#propuesta_ciudadana', 'data-toggle' => "tab"} Propuesta ciudadana
              %li
                %a{href: '#objetivos', 'data-toggle' => "tab"} Objetivos
              %li
                %a{href: '#candidatos', 'data-toggle' => 'tab'} Candidatos
              
            .tab-content
              #centro_de_noticias.tab-pane.active
                .page-header
                  %h3 Centro de noticias

                %dl
                  %dt Titulo:
                  %dd= Setting.centro_de_noticas_title.present? ? Setting.centro_de_noticas_title : 'No se esta mostrando'
                  
                  %dt Subtitulo:
                  %dd= Setting.centro_de_noticas_subtitle.present? ? Setting.centro_de_noticas_subtitle : 'No se esta mostrando'
                  
                  %dt Activo:
                  %dd
                    - if Setting.centro_de_noticas_visible
                      %span.label.label-success
                        Si
                    - else
                      %span.label.label-important
                        No
                  
                - if Setting.centro_de_noticas_title.blank? || !Setting.centro_de_noticas_visible
                  .alert.alert-error
                    %strong ¡Atenci&oacute;n!
                    Para habilitar la secci&oacute;n debe de estar activa y tener un titulo.
              
              #centro_educacional.tab-pane
                .page-header
                  %h3 Centro educacional

                %dl
                  %dt Titulo:
                  %dd= Setting.centro_educacional_title.present? ? Setting.centro_educacional_title : 'No se esta mostrando'
                  
                  %dt Subtitulo:
                  %dd= Setting.centro_educacional_subtitle.present? ? Setting.centro_educacional_subtitle : 'No se esta mostrando'
                  
                  %dt Activo:
                  %dd
                    - if Setting.centro_educacional_visible
                      %span.label.label-success
                        Si
                    - else
                      %span.label.label-important
                        No
                    
                  
                - if Setting.centro_educacional_title.blank? || !Setting.centro_educacional_visible
                  .alert.alert-error
                    %strong ¡Atenci&oacute;n!
                    Para habilitar la secci&oacute;n debe de estar activa y tener un titulo.
              
              #centro_de_debates.tab-pane
                .page-header
                  %h3 Centro de debates

                %dl
                  %dt Titulo:
                  %dd= Setting.centro_de_debates_title.present? ? Setting.centro_de_debates_title : 'No se esta mostrando'
                  
                  %dt Subtitulo:
                  %dd= Setting.centro_de_debates_subtitle.present? ? Setting.centro_de_debates_subtitle : 'No se esta mostrando'
                  
                  %dt Activo:
                  %dd
                    - if Setting.centro_de_debates_visible
                      %span.label.label-success
                        Si
                    - else
                      %span.label.label-important
                        No
                    
                  
                - if Setting.centro_de_debates_title.blank? || !Setting.centro_de_debates_visible
                  .alert.alert-error
                    %strong ¡Atenci&oacute;n!
                    Para habilitar la secci&oacute;n debe de estar activa y tener un titulo.
              
              #propuesta_ciudadana.tab-pane
                .page-header
                  %h3 Propuesta ciudadana

                %dl
                  %dt Titulo:
                  %dd= Setting.propuesta_ciudadana_title.present? ? Setting.propuesta_ciudadana_title : 'No se esta mostrando'
                  
                  %dt Subtitulo:
                  %dd= Setting.propuesta_ciudadana_subtitle.present? ? Setting.propuesta_ciudadana_subtitle : 'No se esta mostrando'
                  
                  %dt Activo:
                  %dd
                    - if Setting.propuesta_ciudadana_visible
                      %span.label.label-success
                        Si
                    - else
                      %span.label.label-important
                        No
                    
                  
                - if Setting.propuesta_ciudadana_title.blank? || !Setting.propuesta_ciudadana_visible
                  .alert.alert-error
                    %strong ¡Atenci&oacute;n!
                    Para habilitar la secci&oacute;n debe de estar activa y tener un titulo.

              
              #objetivos.tab-pane
                .page-header
                  %h3 Objetivos

                %dl
                  %dt Titulo:
                  %dd= Setting.objetivos_title.present? ? Setting.objetivos_title : 'No se esta mostrando'
                  
                  %dt Subtitulo:
                  %dd= Setting.objetivos_subtitle.present? ? Setting.objetivos_subtitle : 'No se esta mostrando'
                  
                  %dt Activo:
                  %dd
                    - if Setting.objetivos_visible
                      %span.label.label-success
                        Si
                    - else
                      %span.label.label-important
                        No
                    
                  
                - if Setting.objetivos_title.blank? || !Setting.objetivos_visible
                  .alert.alert-error
                    %strong ¡Atenci&oacute;n!
                    Para habilitar la secci&oacute;n debe de estar activa y tener un titulo.

              #candidatos.tab-pane
                .page-header
                  %h3 Candidatos

                %dl
                  %dt Titulo:
                  %dd= Setting.candidatos_title.present? ? Setting.candidatos_title : 'No se esta mostrando'
                  
                  %dt Subtitulo:
                  %dd= Setting.candidatos_subtitle.present? ? Setting.candidatos_subtitle : 'No se esta mostrando'
                  
                  %dt Activo:
                  %dd
                    - if Setting.candidatos_visible
                      %span.label.label-success
                        Si
                    - else
                      %span.label.label-important
                        No
                    
                  
                - if Setting.candidatos_title.blank? || !Setting.candidatos_visible
                  .alert.alert-error
                    %strong ¡Atenci&oacute;n!
                    Para habilitar la secci&oacute;n debe de estar activa y tener un titulo.