config/routes.rb
PpPeru::Application.routes.draw do

  
  ComfortableMexicanSofa::Routing.admin(:path => '/admin/cms')

  # get "home/index"

  devise_for :users

  # root :to => "home#index"
  
  resources :usuarios, controller: :users do
    resources :seguidores, controller: 'users_activities/followers', only: [:create, :destroy]
  end

  match '/auth/:provider/callback', to: 'authentications#create'


  resources :topics, only: [:index]
  
  resources :news_actors, only: [:show, :index] do
    collection do
      post :rates
    end
  end

  scope '/centro_de_medios' do
    resources :noticias, controller: :news, only: [:show, :index] do
      resources :comentarios, controller: :annotations, only: [:create, :new]
      collection do
        post :rates
      end
    end
  end
  
  scope '/centro_educacional' do
    resources :entradas, controller: :entries, only: [:show, :index] do
      resources :comentarios, controller: :annotations, only: [:create, :new]
    end
  end
  
  scope '/centro_de_debate' do
    resources :debates, controller: :discussions, only: [:show, :index] do
      resources :comentarios, controller: :annotations, only: [:create, :new]
      resources :votes, controller: 'discussions_activities/votes', only: :create
    end
  end
  
  scope '/propuesta_ciudadana' do
    resources :propuestas, controller: :proposals, except: :destroy do
      resources :comentarios, controller: :annotations, only: [:create, :new]
      resources :votes, controller: 'proposals_activities/votes', only: :create
    end
  end
  
  scope '/objetivos_estrategicos' do
    resources :buenas_practicas, controller: :strategic_objectives, only: [:index]
    resources :objetivos, controller: :objectives, only: [:index]
  end

  scope '/actores_politicos' do
    resources :candidatos, controller: :news_actors, only: [:index, :show]
  end
  
  
  
  resources :annotations, only: :index do
    resources :reports, only: :create
    resources :reviews_admins, only: :create
  end

  namespace :admin do
    root to: 'home#index'
    resources :news do
      resource :publish, controller: 'news_actions/publish', only: :create
      resource :archive, controller: 'news_actions/archive', only: :create
    end
    
    resources :discussions do
      resources :open_discussion, controller: 'discussions_actions/open_discussion', only: :create
      resources :close_discussion, controller: 'discussions_actions/close_discussion', only: :create
      resources :archive_discussion, controller: 'discussions_actions/archive_discussion', only: :create
    end
    

    resources :proposals do
      resource :publish, controller: 'proposals_actions/publish', only: :create
      resource :archive, controller: 'proposals_actions/archive', only: :create
    end

    resources :entries do
      resource :publish, controller: 'entries_actions/publish', only: :create
      resource :archive, controller: 'entries_actions/archive', only: :create
    end
    
    resources :topics, only: [:index, :create]
    resources :news_actors
    resources :groups
    resources :users
    resources :attendees
    resource :configuration, only: [:show, :edit, :update]
    resources :strategic_objectives do
      resources :annotations, only: [:create, :new]
    end
    
    resources :roles, only: :index do
      resources :role_permissions, only: [:index, :create]
    end
  end

  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :birthday, :dni, :gender, :instruction, :name, :province_id, :state_id
  validates :name, presence: true
  has_and_belongs_to_many :strategic_objectives
  
  GENDER = [{id: 1, name: 'Masculino'}, {id: 2, name: 'Femenino'}]
  
end

app/controllers/admin/attendees_controller.rb
class Admin::AttendeesController < Admin::BaseController
  before_filter :find_attendee, only: [:edit, :update, :destroy, :show]
  
  def index
    @attendees = Attendee.scoped
    respond_to do |format|
      format.html
      format.json {render json:  @attendees.where("name like ?", "%#{params[:q]}%")}
    end
  end
  
  def new
    @attendee = Attendee.new
  end
  
  def edit
  end
  
  def update
    if @attendee.update_attributes(params[:attendee])
      redirect_to admin_attendees_path, notice: 'Actualizado Correctamente'
    else
      render :edit
    end
  end
  
  def show
  end
  
  
  def create
    @attendee = Attendee.new(params[:attendee])
    if @attendee.save
      redirect_to find_response_by_referer
    else
      render :new
    end
  end
  
  def destroy
    @attendee.destroy
    redirect_to admin_attendees_path, notice: 'Asistente Eliminado'
  end
  
  private
  def find_attendee
    @attendee = Attendee.find params[:id]
  end
  
  def find_response_by_referer
    (URI(request.referer).path.eql? '/admin/attendees/new') ? admin_attendees_path : admin_strategic_objectives_path
  end
end

app/helpers/admin/attendees_helper.rb
module Admin::AttendeesHelper
end

app/views/admin/attendees/_form.html.haml
= form_for [:admin, attendee], validate: true,  html: {class: 'form-horizontal'} do |f|
	.control-group
		.control-label
			= f.label :name, 'Nombre:'
		.controls
			= f.text_field :name
	.control-group
		.control-label
			= f.label :sexo, 'Sexo:'
		.controls
			= f.select :gender, Attendee::GENDER.collect {|gender| [gender[:name], gender[:id]]}
	.control-group
		.control-label
			= f.label :birthday, 'Fecha De Nacimiento:'
		.controls
			= f.text_field :birthday
	.control-group
		.control-label
			= f.label :instruction, 'Institucion'
		.controls
			= f.text_field :instruction
	.control-group
		.control-label
			= f.label :dni, 'DNI:'
		.controls
			= f.text_field :dni
	.control-group
		.control-label
			= f.label :estate, 'Estado:'
		.controls
			= f.select :state_id, State.all.collect {|state| [state.name.humanize, state.id]}
	.control-group
		.control-label
			= f.label :province, 'Providencia:'
		.controls
			= f.select :province_id, Province.all.collect {|province| [province.name.try(:humanize), province.id]}

	.control-group
		.controls
			= f.submit (attendee.new_record? ? 'Crear' : 'Actualizar'), class: [:btn, 'btn-primary']

app/views/admin/attendees/edit.html.haml
.row-fluid
	.box
		.box-content
			.page-header
				%h1 Centro de Asistentes
				= render 'form', {attendee: @attendee}

app/views/admin/attendees/index.html.haml
.row-fluid
	.box
		.box-content
			.page-header
				%h1 Asistentes
				- if can? :create, Attendee
					= link_to new_admin_attendee_path, :class => 'btn-add-resource btn btn-primary' do
						%i.icon-white.icon-plus
						Nuevo Asistente
			%table.table.table-striped.table-bordered
				%thead
					%tr
						%th ID
						%th Nombre
						%th Acciones
				%tbody
					- @attendees.each do |a|
						%tr
							%td.center= a.id
							%td= a.name
							%td
								- if can? :update, Attendee
									= link_to edit_admin_attendee_path(a), :class => 'btn btn-mini btn-primary' do
										%i.icon-edit.icon-white
										Editar
								- if can? :destroy, Attendee
									= link_to admin_attendee_path(a), :method => :delete, :confirm => 'Esta seguro?', :class => 'btn btn-danger btn-mini' do
										%li.icon-white.icon-remove
										Eliminar

app/views/admin/attendees/new.html.haml
.row-fluid
	.box
		.box-content
			.page-header
				%h1 Centro de Asistente
				= render 'form', {attendee: Attendee.new}